apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - GPU
        - HostDevices
      logVerbosity:
        virtLauncher: 4
        virtHandler: 4
        virtController: 4
        virtAPI: 5
        virtOperator: 6
    permittedHostDevices:
      usbDevices:
      - usbBusPortSelector: "1-9"
        resourceName: "generic.com/hid-mouse"
        externalResourceProvider: false
      # - usbBusDevSelector: "001-003"
      #   resourceName: "generic.com/hid-mouse"
      #   externalResourceProvider: false
      # pciHostDevices:
      # - pciVendorSelector: "8086:4680"
      #   resourceName: "intel.com/sriov-gpudevice"
      #   externalResourceProvider: false
